# -*- coding: utf-8 -*-
"""DETECCAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCyb7ob2taTkIa1GQRkVx8uyPnHttyX7
"""

# -*- coding: utf-8 -*-
"""DETECCAR: Detecção de Veículos e Controle de Semáforos Inteligentes com YOLOv8"""

# 📌 Importação das bibliotecas necessárias
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import warnings
import yaml
from PIL import Image
from ultralytics import YOLO
from IPython.display import Video, display

warnings.filterwarnings('ignore')  # Removendo avisos desnecessários

# 📌 Configuração do Seaborn para visualização de gráficos
sns.set(rc={'axes.facecolor': '#eae8fa'}, style='darkgrid')

# 📌 Caminhos dos arquivos (ajuste conforme o seu diretório)
DATASET_PATH = '/content/drive/MyDrive/Colab Notebooks/Banco de Dados'
VIDEO_PATH = '/content/drive/MyDrive/Colab Notebooks/transito.mp4'  # 📌 Caminho do vídeo
MODEL_PATH = 'yolov8n.pt'  # 📌 Modelo YOLOv8 pré-treinado

# 📌 Parâmetros do Semáforo Inteligente
SEMAPHORE_PARAMS = {
    'tempo_verde_base': 30,
    'tempo_vermelho_pedestre': 15,
    'limite_veiculos_prioridade': 8,
    'tempo_emergencia': 20
}

# 📌 Carregar Modelo YOLO
model = YOLO(MODEL_PATH)

# 📌 Classe de Controle do Semáforo Inteligente
class TrafficLightController:
    def __init__(self, params):
        self.params = params
        self.current_state = {'via_principal': 'VERDE', 'via_secundaria': 'VERMELHO'}

    def update_state(self, veiculos, pedestres, emergencia):
        if emergencia:
            self.current_state = {'via_principal': 'VERDE', 'via_secundaria': 'VERMELHO'}
            return self.params['tempo_emergencia']
        if pedestres:
            self.current_state = {'via_principal': 'VERMELHO', 'via_secundaria': 'VERDE'}
            return self.params['tempo_vermelho_pedestre']
        if veiculos > self.params['limite_veiculos_prioridade']:
            return self.params['tempo_verde_base'] + 10
        return self.params['tempo_verde_base']

# 📌 Simulação de Cenários para Testes
class TrafficSimulator:
    def generate_scenario(self, scenario_type):
        if scenario_type == 'rush_hour':
            return {'veiculos': random.randint(10, 20), 'pedestres': False, 'emergencia': False}
        elif scenario_type == 'emergency':
            return {'veiculos': 5, 'pedestres': False, 'emergencia': True}
        elif scenario_type == 'pedestrian':
            return {'veiculos': 3, 'pedestres': True, 'emergencia': False}
        else:
            return {'veiculos': 0, 'pedestres': False, 'emergencia': False}

# 📌 Função para Detecção de Veículos em Vídeo com Cenários
def detectar_veiculos_video(video_path, output_path="processed_video.mp4"):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Não foi possível abrir o vídeo: {video_path}")

    # Configurações do vídeo
    frame_width, frame_height = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (frame_width, frame_height))

    # Inicializar controlador de semáforo e simulador
    controller = TrafficLightController(SEMAPHORE_PARAMS)
    simulator = TrafficSimulator()

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Detecção de veículos
        results = model.predict(frame, imgsz=640, conf=0.7)
        veiculos = len(results[0].boxes)
        emergencia = 'ambulance' in results[0].names  # Verifica presença de ambulância

        # 🔹 Escolher um cenário aleatório a cada frame
        scenario_type = random.choice(["rush_hour", "emergency", "pedestrian"])
        scenario = simulator.generate_scenario(scenario_type)

        # 🔹 Aplicar controle do semáforo baseado no cenário
        tempo_verde = controller.update_state(
            veiculos=scenario['veiculos'],
            pedestres=scenario['pedestres'],
            emergencia=scenario['emergencia']
        )

        # 🔹 Anotação do frame com o cenário e tempo de semáforo
        frame = results[0].plot()
        cv2.putText(frame, f"Cenario: {scenario_type} | Estado: {controller.current_state} | Tempo: {tempo_verde}s",
                    (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

        # Salva o frame processado
        out.write(frame)

    cap.release()
    out.release()
    print(f"✅ Vídeo processado salvo em: {output_path}")

    # Exibir vídeo processado
    display(Video(output_path, embed=True, width=640))

# 📌 Teste de Cenários de Tráfego
def testar_cenarios():
    test_cases = [
        ('rush_hour', 'Aumentar tempo verde para aliviar trânsito'),
        ('emergency', 'Priorizar via principal para veículos de emergência'),
        ('pedestrian', 'Ativar vermelho para veículos e permitir travessia de pedestres')
    ]

    controller = TrafficLightController(SEMAPHORE_PARAMS)
    simulator = TrafficSimulator()

    print("\n🔎 **Testando cenários do semáforo inteligente:**\n")

    for cenario, descricao in test_cases:
        dados = simulator.generate_scenario(cenario)
        tempo = controller.update_state(**dados)
        print(f"🚦 [Cenario: {cenario}] {descricao} | Tempo ajustado: {tempo}s")

# 🔹 Testar os cenários
testar_cenarios()

if __name__ == "__main__":
    testar_cenarios()  # Testar os cenários simulados de tráfego
    detectar_veiculos_video(VIDEO_PATH)  # Processar o vídeo do trânsito

# Baixando vídeo caso não apareça na célula anterior
from google.colab import files

# Caminho do vídeo processado (ajuste se necessário)
video_path = "processed_video.mp4"

# Baixar o vídeo
files.download(video_path)